spring.application.name=FoodProductionManagement

# DataSource (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/foodapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Tokyo
spring.datasource.username=foodapp_user
spring.datasource.password=foodapp_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Logging (SQL parameter)
logging.level.org.hibernate.type.descriptor.sql=trace

# SQL initialization
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true